<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Metadatos del ejecutable -->
    <AssemblyTitle>Sistema de Evaluación de Madurez Tecnológica</AssemblyTitle>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Company>Angelo Rivero</Company>
    <Product>MadurezTecnologica</Product>
    <Copyright>© 2026 Angelo Rivero</Copyright>

    <!-- Compresión para reducir tamaño del exe final -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- Copia appconfi.json al lado del .exe en cada publish -->
    <None Update="appconfi.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Recursos\Logos\" />
    <Folder Include="Recursos\Iconos\" />
  </ItemGroup>

</Project>